
**Copyright**

This notebook was created as part of the "Deep learning / VITMMA19" class at
Budapest University of Technology and Economics, Hungary,

TensorBoard vs TensorBoardX: https://tensorboardx.readthedocs.io/en/latest/tutorial.html

Any re-use or publication of any part of the notebook is only allowed with the
written consent of the authors.

2025 (c) Mohammed Salah Al-Radhi, Bálint Gyires-Tóth



**Check TensorFlow Version**

Ensure TensorFlow is installed and check its version with the following code:

In [1]:
import tensorflow as tf
print(tf.__version__)


2.17.0


You should see the TensorFlow version printed. TensorFlow 2.x is what we will be using.

**Understanding Tensors in TensorFlow**

Tensors are the primary data structure in TensorFlow. They are essentially multi-dimensional arrays.

**1- Creating Tensors:**

In [2]:
# Scalar (rank-0 tensor)
scalar = tf.constant(7)
print("Scalar:", scalar)

# Vector (rank-1 tensor)
vector = tf.constant([1.0, 2.0, 3.0])
print("Vector:", vector)

# Matrix (rank-2 tensor)
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

# 3D Tensor (rank-3 tensor)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:", tensor_3d)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


**2- Tensor Properties:**

In [3]:
print("Shape of matrix:", matrix.shape)
print("Data type of matrix:", matrix.dtype)


Shape of matrix: (2, 2)
Data type of matrix: <dtype: 'int32'>


**3- Basic TensorFlow Operations**

In [5]:
# Element-wise addition
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.add(a, b)
print("Element-wise addition:", c)

# Element-wise multiplication
d = tf.multiply(a, b)
print("Element-wise multiplication:", d)


Element-wise addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Element-wise multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


**4- Matrix Operations:**

In [6]:
# Matrix multiplication
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
product = tf.matmul(matrix1, matrix2)
print("Matrix multiplication result:\n", product)


Matrix multiplication result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


**5- Reshaping Tensors:**

In [7]:
# Reshaping a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tf.reshape(tensor, [3, 2])
print("Original Tensor:\n", tensor)
print("Reshaped Tensor:\n", reshaped_tensor)


Original Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


**6- Slicing Tensors:**

In [8]:
# Slicing a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sliced_tensor = tensor[:, 1:]
print("Original Tensor:\n", tensor)
print("Sliced Tensor:\n", sliced_tensor)


Original Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Sliced Tensor:
 tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


**Working with Variables**

Variables in TensorFlow are used to store mutable data.

**1- Creating and Using Variables:**

In [9]:
# Create a variable
var = tf.Variable([1.0, 2.0, 3.0])
print("Initial value of variable:", var.numpy())

# Assign a new value to the variable
var.assign([4.0, 5.0, 6.0])
print("New value of variable:", var.numpy())

# Perform in-place operations
var.assign_add([1.0, 1.0, 1.0])
print("After addition:", var.numpy())


Initial value of variable: [1. 2. 3.]
New value of variable: [4. 5. 6.]
After addition: [5. 6. 7.]


**Automatic Differentiation with TensorFlow**

TensorFlow’s `tf.GradientTape` allows for automatic differentiation, which is essential for optimization tasks.

**Calculating Gradients:**

In [10]:
# Define a simple function: y = x^2
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

# Compute the gradient of y with respect to x
grad = tape.gradient(y, x)
print("Gradient of y = x^2 with respect to x:", grad.numpy())


Gradient of y = x^2 with respect to x: 6.0
